### ISSUE TITLE
Update to current docker files as used in the integration tests

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/ZendroStarterPack#1]
The two code generators used for [the GraphQL server](https://github.com/ScienceDb/graphql-server-model-codegen) and for [the single page application](https://github.com/ScienceDb/single-page-app-codegen) have integration test suites that use Docker to run the tests.

The respective Docker files are more up to date than those within this Starter-Pack. Please update the files accordingly.

### Expected work time: 2h

**Comment by YKolokoltsev** [comment]
Closed for a long time ago
