### ISSUE TITLE
Update the docker-compose files to work with the react branches of the SPA

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/ZendroStarterPack#4]
Create a new branch of the StarterPack called exactly as the React.js branches in the projects 
* [single-page-app-codegen](https://github.com/ScienceDb/single-page-app-codegen) and
* [single-page-app](https://github.com/ScienceDb/single-page-app)

are called.

Within this new branch adjust the docker-compose files:
* docker-compose-dev.yml
* docker-compose.yml

So they work with the new React interface. Update the Readme also!

This should prepare the soon to be made merge into master.

### Expected work time: 2h

**Comment by framirez07** [comment]
Completed at commits:
[i4 - Configurations added to work with react-branches](https://github.com/ScienceDb/ScienceDbStarterPack/commit/60d2d54aa54186893bd27e6df7f6ed177886c05d)
[i4 - docker-compose files version fixed](https://github.com/ScienceDb/ScienceDbStarterPack/commit/e2fd23e12dde2b3ac31e99fc94eabb77bf94f3f9)
[i4 - Readme.md updated](https://github.com/ScienceDb/ScienceDbStarterPack/commit/8083c0fda8977ce619b97c56959f0dad5235bec1)


The following are the steps to get running the starter pack with the react version of the SPA:

**#--clone & checkout to react branch.**
```
git clone https://github.com/ScienceDb/ScienceDbStarterPack.git
cd ScienceDbStarterPack
git checkout i25-starter-pack-react
```

**#-- init submodules**
`git submodule update --init --remote`


**#-- copy seeders**
`cp -r ./seeders ./graphql-server`


**#-- generate code**
```
docker run --rm -it -v `pwd`:/opt --user <your_uid>:<your_gid> sciencedb-code-generators:latest 
    graphql-server-model-codegen --jsonFiles /opt/data_model_definitions -o /opt/graphql-server
    single-page-app-codegen --jsonFiles /opt/data_model_definitions -o /opt/single-page-app
    exit
```

**#-- start**
`docker-compose -f docker-compose-dev.yml up --force-recreate --remove-orphans
`
