### ISSUE TITLE
Do the freeze for the first alpha-0.1.0 and latest-stable

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/ZendroStarterPack#6]
### Define and publish the first stable version

This issue affects at least five sub-projects. The skeleton projects, the code-generators, and this Starter-Pack. 

#### Merge all feature branches into master

In the affected projects merge all feature branches, that belong into stable, into master. 

#### Tag the respective versions

Then, tag this version as `0.1.0` and `latest-stable`. The latter is somewhat questionable according to [semantic versioning](https://semver.org/).

```sh
git tag -fa '0.1.0' -m 'Current stable and first alpha version. Yeah!'
git tag -fa 'latest-stable' -m 'Current stable and first alpha version. Yeah!'
```

#### Adjust usage to latest-stable

Especially in the Sandbox adjust the `git clone` commands to the above `latest-stable` tag. Use `latest-stable` instead of `0.1.0` to implement inherent usage of the latest stable version in the future when possibly new versions are tagged as latest stable. 

#### Check other projects 

Check the skeleton and code generator projects, especially the integration tests. Maybe the adjustment to using "latest stable" needs to be done there, too. If so, implement it, please.

**Comment by coeit** [comment]
set package.json version numbers to 0.1.0
